### ISSUE TITLE
Create interface that contain all chargepoint.api.client struct public methods

### ISSUE THREAD

**Issue by difince** [CamusEnergy/kinney#28]
I want to request the creation of Interface that contains all public methods of client struct https://github.com/CamusEnergy/kinney/blob/31bf5a51a1378f4c9e2284739ac353a4f5aa12d3/controller/chargepoint/api/client.go#L20

This new interface with supposed name EVChargerPointClient  will define all methods:

```
type EVChargerPointClient interface {
	GetCPNInstances(ctx context.Context, req *schema.GetCPNInstancesRequest) (*schema.GetCPNInstancesResponse, error)
	GetStations(ctx context.Context, req *schema.GetStationsRequest) (*schema.GetStationsResponse, error)
	GetStationGroups(ctx context.Context, req *schema.GetStationGroupsRequest) (*schema.GetStationGroupsResponse, error) 
        ShedLoad(ctx context.Context, req *schema.ShedLoadRequest) (*schema.ShedLoadResponse, error)
        ClearShedState(ctx context.Context, req *schema.ClearShedStateRequest) (*schema.ClearShedStateResponse, error)
        GetLoad(ctx context.Context, req *schema.GetLoadRequest) (*schema.GetLoadResponse, error)
}
```

Then the signature of NewClient function will be changed to return the EVChargerPoint interface instead of private client: 
`func NewClient(url, apiKey, apiPassword string, httpLogWriter io.Writer) EVChargerPoint `

`func NewClient(url, apiKey, apiPassword string, httpLogWriter io.Writer) *client `

By doing this all clients that want to use the API won't be forced to create (call) NewClient for each request that they want to execute.

**Comment by difince** [comment]
@powerduncan

**Comment by powerduncan** [comment]
in go, interfaces are generally defined for the *consumer*, and not the *producer* ([source](https://github.com/golang/go/wiki/CodeReviewComments#interfaces)).  a concrete application of that, is that functions should generally return concrete types, and it is up to the consumer to use an interface as necessary.  even further, it is often more appropriate for the consumer to define the interface itself, rather than the producer doing it.

if i'm reading this correctly, i think the underlying problem is that it is currently impossible to define a variable *with a type* that can point to a `client` instance (in particular, in a struct instance for as a function parameter, since `foo := NewClient()` and `var foo = NewClient()` both handle the type inference).  there are two solutions to this.  one: you can define an interface *adjacent* to the real struct purely for use by the caller.  for example, in `client.go`:

```go
type Client interface {
    GetCPNInstances(context.Context, *schema.GetCPNInstancesRequest) (*schems.GetCPNInstancesResponse, error)
    ...
}

func NewClient(url, apiKey, ...) *client { ... }
```

now, the consumer can do:

```go
func DoWork(client api.Client, ...) { ... }
func OtherFunction() {
    DoWork(api.NewClient(...))
}

// or...

type Foo struct {
    Client api.Client
}

func FooFunction() {
    foo := Foo{Client: api.NewClient()}
}
```

this interface can also be defined in the consumer code and used in the same way.

the other option is to simply export the `client` type.  change `type client struct {` to `type Client struct {`, and now the consumer can reference that type :)

**Comment by difince** [comment]
Thank you @powerduncan for the explanation. You got my problem. Now, all the tutorials I have read about interfaces make sense.
I like that the `client` is not exported, and lets stay this way. I will close this issue and I will create the interface on my side.
